### ISSUE TITLE
I followed all steps of tutorial, but still getting this error.

### ISSUE THREAD

**Issue by azeemgujjar** [londonappbrewery/Clima-Flutter-Completed#10]
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _TypeError was thrown building Builder:
type 'int' is not a subtype of type 'double'

The relevant error-causing widget was: 
  MaterialApp file:///D:/Clients/experiments/Clima-Flutter/lib/main.dart:9:12
When the exception was thrown, this was the stack: 
#0      _LocationScreenState.updateUI.<anonymous closure> (package:clima/screens/location_screen.dart:36:14)
#1      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
#2      _LocationScreenState.updateUI (package:clima/screens/location_screen.dart:28:5)
#3      _LocationScreenState.initState (package:clima/screens/location_screen.dart:24:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Please help

**Comment by azeemgujjar** [comment]
i find the issue, actually sometimes if weather value is not in double type this through error, seems dart is not that smart as other popular old languages. i don't know why google choose this garbage.
i change my variable type from double to "var" and this fixes the issue.

**Comment by kiranojhanp** [comment]
> i find the issue, actually sometimes if weather value is not in double type this through error, seems dart is not that smart as other popular old languages. i don't know why google choose this garbage.
> i change my variable type from double to "var" and this fixes the issue.

because its also a strongly typed language?
