### ISSUE TITLE
followed the ful tutorial but i am getting this error

### ISSUE THREAD

**Issue by himanshu-1034** [londonappbrewery/Clima-Flutter-Completed#14]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building LocationScreen(dirty, state:
_LocationScreenState#8c194):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 360 pos 10: 'data != null'

The relevant error-causing widget was:
  LocationScreen
  file:///G:/app%20brewery%20flutter/savd%20projects/weather_forcasting_app/lib/screens/loading_screen.dart:26:15

When the exception was thrown, this was the stack:
#2      new Text (package:flutter/src/widgets/text.dart:360:10)
#3      _LocationScreenState.build (package:weather_forcasting_app/screens/location_screen.dart:103:21)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (132 frames)
#142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#144    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5624:32)
#145    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6001:17)
#146    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#148    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#149    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#150    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#154    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
#155    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#157    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
#158    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#160    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#161    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#162    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#164    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
#165    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#166    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#169    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#170    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#174    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#177    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#179    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#180    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#181    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#182    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#183    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#184    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#188    _invoke (dart:ui/hooks.dart:253:10)
#189    _drawFrame (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building LocationScreen(dirty, state: _LocationScreenState#8c194):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 360 pos 10: 'data != null'

The relevant error-causing widget was: 
  LocationScreen file:///G:/app%20brewery%20flutter/savd%20projects/weather_forcasting_app/lib/screens/loading_screen.dart:26:15
When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:360:10)
#3      _LocationScreenState.build (package:weather_forcasting_app/screens/location_screen.dart:103:21)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
i need help

**Comment by sandeep1dimri** [comment]
> 'package:flutter/src/widgets/text.dart':
> Failed assertion: line 360 pos 10: 'data != null'

error is at:
'package:flutter/src/widgets/text.dart':
Failed assertion: line 360 pos 10: 'data != null'

this widget is getting null data, and error being thrown from constructor of the text widget. Pls check if you can figure out, otherwise you need to share that code file. i will load my project  next week but i made many changes so it might not be same as the one we have on tutorial. Let me know i can send you a particular file.

https://api.flutter.dev/flutter/widgets/Text/Text.html
}) : assert(
       data != null,
       'A non-null String must be provided to a Text widget.',
     ),
